/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package firstone.cliente.presentacion;

import com.firstonesoft.client.Client;
import firstone.cliente.ccs.InterfazEnvioCliente;
import firstone.serializable.Aviso;
import firstone.cliente.datos.model.Bitacora;
import firstone.cliente.datos.model.Guardia;
import firstone.cliente.datos.model.Tranca;
import firstone.cliente.negocio.BitacoraNegocio;
import java.util.Date;
import javax.swing.JOptionPane;


/**
 *
 * @author Milton
 */
public class LanzarAviso extends javax.swing.JFrame {

    BitacoraNegocio bitacoraNegocio;
    
    InterfazEnvioCliente interfazEnvioCliente;
    
    Tranca tranca;
    Guardia guardia;
    /**
     * Creates new form LanzarAviso
     */
    public LanzarAviso(Tranca tranca, Guardia guardia, Client cliente) {
        initComponents();
        bitacoraNegocio = new BitacoraNegocio();
        interfazEnvioCliente = new InterfazEnvioCliente(cliente,guardia.getCi());
        
        this.tranca = tranca;
        this.guardia = guardia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jrb_trancas = new javax.swing.JRadioButton();
        jrb_propietarios = new javax.swing.JRadioButton();
        jrb_todos = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtext_mensaje = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        buttonGroup1.add(jrb_trancas);
        jrb_trancas.setSelected(true);
        jrb_trancas.setText("Todas las Trancas");

        buttonGroup1.add(jrb_propietarios);
        jrb_propietarios.setText("Todos los propietarios");

        buttonGroup1.add(jrb_todos);
        jrb_todos.setText("Todos");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("¿A quienes desea enviar el Aviso?");

        jtext_mensaje.setColumns(20);
        jtext_mensaje.setRows(5);
        jScrollPane1.setViewportView(jtext_mensaje);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Mensaje");

        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jrb_todos, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jrb_trancas, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jrb_propietarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrb_todos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrb_trancas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrb_propietarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        Aviso aviso = new Aviso();
        aviso.setFrom(guardia.getNombre()+" "+guardia.getApellido());
        aviso.setFecha_hora((new Date()).getTime());
        aviso.setMensaje(jtext_mensaje.getText());
        
        if (jrb_todos.isSelected())
            aviso.setTo(Aviso.DIRIGIDO_TODOS);
        else if (jrb_trancas.isSelected())
            aviso.setTo(Aviso.DIRIGIDO_TRANCAS);
        else
            aviso.setTo(Aviso.DIRIGIDO_PROPIETARIOS);
        if (interfazEnvioCliente.lanzarAviso(aviso,tranca.getId_entorno()))
        {
            registrarBitacoraGuardia(Bitacora.ACCION_LANZAR_AVISO, "Enviar un aviso  MENSAJE :"+ aviso.getMensaje());
            this.setVisible(false);
        }else
        {
            JOptionPane.showMessageDialog(rootPane, "Problemas al enviar Aviso, no se pudo completar", "Enviar Aviso", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LanzarAviso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LanzarAviso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LanzarAviso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LanzarAviso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LanzarAviso(new Tranca(),new Guardia()).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jrb_propietarios;
    private javax.swing.JRadioButton jrb_todos;
    private javax.swing.JRadioButton jrb_trancas;
    private javax.swing.JTextArea jtext_mensaje;
    // End of variables declaration//GEN-END:variables

    
    private void registrarBitacoraGuardia(String accion, String detalle) {
        Bitacora bitacora = new Bitacora();
        bitacora.setAccion(accion);
        bitacora.setCi_guardia(guardia.getCi());
        bitacora.setDetalle(detalle);
        bitacora.setFecha_hora(new Date());
        bitacoraNegocio.registrarBitacora(bitacora);
    }

}
